#! /bin/sh

sxhkd &
compton &
bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config bottom_padding 58
bspc config top_padding 32


